/* Generated by scripts/init.mjs — do not edit by hand. */
import type { ComponentType } from 'react';

export type RemoteModule = {
  default?: ComponentType<{ embedded?: boolean }>;
  Demo?: ComponentType<{ embedded?: boolean }>;
};

export type RemoteLoader = () => Promise<RemoteModule>;

export const remoteLoaders: Record<string, RemoteLoader> = {
  demoRemote: () =>
    // @ts-expect-error Module Federation remote — resolved at runtime
    import('demoRemote/Demo') as Promise<RemoteModule>,
};
