/* Generated by init / add-remote — do not edit by hand. */
import type { ComponentType } from 'react';

export type RemoteModule = {
  default?: ComponentType<Record<string, unknown> & { embedded?: boolean }>;
  App?: ComponentType<Record<string, unknown> & { embedded?: boolean }>;
  [exportName: string]:
    ComponentType<Record<string, unknown> & { embedded?: boolean }> | undefined;
};

export type RemoteLoader = () => Promise<RemoteModule>;

export const remoteLoaders: Record<string, RemoteLoader> = {
  demoRemote: () =>
    // @ts-expect-error Module Federation remote — resolved at runtime
    import('demoRemote/DemoRemote') as Promise<RemoteModule>,
};
