import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div style={{
          fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
          display: 'flex',
          maxWidth: '1280px',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}>
          <header className="header" style={{ background: "#1976d2", padding: "1rem", color: "#fff", textAlign: "center" }}>
            <nav>
              <Link href="/" style={{ color: "#fff", marginRight: "2rem", textDecoration: "none", fontWeight: 500 }}>
                Home
              </Link>
              <Link href="/about" style={{ color: "#fff", marginRight: "2rem", textDecoration: "none", fontWeight: 500 }}>
                About
              </Link>
              <Link href="/events" style={{ color: "#fff", textDecoration: "none", fontWeight: 500 }}>
                Events
              </Link>
            </nav>
          </header>
          <main style={{ padding: "1rem", margin: "0 auto" }}>
            {children}
          </main>
          <footer style={{ background: "#1976d2", padding: "1rem", color: "#fff", textAlign: "center", marginTop: "2rem" }}>
            <p style={{ margin: 0, fontSize: "0.9rem" }}>© 2024 Content Compare. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
