/**
 * Shell remotes[] helpers shared by init + webpack (CJS).
 */
const {
  DEFAULT_REMOTE_NAME,
  isValidPackageName,
  toFederationName,
} = require('./app-name.cjs');

const DEFAULT_EXPOSE = './Demo';
const DEMO_ALIAS = 'demoRemote';
const DEMO_URL_ENV = 'DEMO_REMOTE_URL';

function aliasToUrlEnv(alias) {
  if (alias === DEMO_ALIAS) return DEMO_URL_ENV;
  return (
    String(alias)
      .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replace(/[^a-zA-Z0-9]+/g, '_')
      .toUpperCase() + '_URL'
  );
}

function isValidAlias(alias) {
  return typeof alias === 'string' && /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(alias);
}

function isValidExpose(expose) {
  return typeof expose === 'string' && /^\.\/[A-Za-z0-9/_-]+$/.test(expose);
}

function isValidUrlEnv(urlEnv) {
  return typeof urlEnv === 'string' && /^[A-Z][A-Z0-9_]*$/.test(urlEnv);
}

/** @returns {{ alias: string, name: string, federationName: string, expose: string, urlEnv: string }} */
function defaultDemoRemote(name = DEFAULT_REMOTE_NAME) {
  return {
    alias: DEMO_ALIAS,
    name,
    federationName: toFederationName(name),
    expose: DEFAULT_EXPOSE,
    urlEnv: DEMO_URL_ENV,
  };
}

/**
 * Normalize one remote entry (fills federationName / defaults).
 * @param {object} entry
 */
function normalizeRemoteEntry(entry) {
  if (!entry || typeof entry !== 'object') {
    throw new Error('Remote entry must be an object');
  }
  const alias = entry.alias || DEMO_ALIAS;
  const name = entry.name || alias;
  const expose = entry.expose || DEFAULT_EXPOSE;
  const urlEnv = entry.urlEnv || aliasToUrlEnv(alias);
  const federationName =
    entry.federationName || toFederationName(name);

  if (!isValidAlias(alias)) {
    throw new Error(`Invalid remote alias: ${alias}`);
  }
  if (!isValidPackageName(name)) {
    throw new Error(`Invalid remote name: ${name}`);
  }
  if (!isValidExpose(expose)) {
    throw new Error(`Invalid remote expose: ${expose}`);
  }
  if (!isValidUrlEnv(urlEnv)) {
    throw new Error(`Invalid remote urlEnv: ${urlEnv}`);
  }
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(federationName)) {
    throw new Error(`Invalid remote federationName: ${federationName}`);
  }

  return { alias, name, federationName, expose, urlEnv };
}

/**
 * Resolve remotes[] from metadata, including legacy remoteName fields.
 * @param {object} meta
 */
function remotesFromMeta(meta = {}) {
  if (Array.isArray(meta.remotes) && meta.remotes.length > 0) {
    return meta.remotes.map((r) => normalizeRemoteEntry(r));
  }
  if (meta.remoteName || meta.remoteFederationName) {
    return [
      normalizeRemoteEntry({
        alias: DEMO_ALIAS,
        name: meta.remoteName || DEFAULT_REMOTE_NAME,
        federationName:
          meta.remoteFederationName ||
          toFederationName(meta.remoteName || DEFAULT_REMOTE_NAME),
        expose: DEFAULT_EXPOSE,
        urlEnv: DEMO_URL_ENV,
      }),
    ];
  }
  return [defaultDemoRemote()];
}

/**
 * Parse `--remote=alias:name[:expose[:urlEnv]]`.
 * @param {string} spec
 */
function parseRemoteFlag(spec) {
  if (!spec || typeof spec !== 'string') {
    throw new Error('Empty --remote value');
  }
  const parts = spec.split(':');
  if (parts.length < 2) {
    throw new Error(
      'Invalid --remote. Use alias:name[:expose[:urlEnv]] (e.g. demoRemote:my-checkout)',
    );
  }
  const alias = parts[0];
  const name = parts[1];
  let expose = DEFAULT_EXPOSE;
  let urlEnv;
  if (parts.length >= 3) {
    // expose may itself contain nothing with colons; remaining optional urlEnv
    if (parts[2].startsWith('./')) {
      expose = parts[2];
      if (parts.length >= 4) urlEnv = parts[3];
    } else if (parts.length === 3 && isValidUrlEnv(parts[2])) {
      urlEnv = parts[2];
    } else {
      throw new Error(
        `Invalid --remote expose (expected ./Module): ${parts[2]}`,
      );
    }
  }
  return normalizeRemoteEntry({ alias, name, expose, urlEnv });
}

/**
 * MF import path: alias + expose without leading "."
 * e.g. demoRemote + ./Demo → demoRemote/Demo
 */
function remoteImportPath(alias, expose) {
  const mod = expose.startsWith('./') ? expose.slice(2) : expose;
  return `${alias}/${mod}`;
}

/**
 * Generate TypeScript loader registry for shell role.
 * @param {Array<{ alias: string, expose: string }>} remotes
 */
function generateLoadersSource(remotes) {
  const lines = [
    '/* Generated by scripts/init.mjs — do not edit by hand. */',
    "import type { ComponentType } from 'react';",
    '',
    'export type RemoteModule = {',
    '  default?: ComponentType<{ embedded?: boolean }>;',
    '  Demo?: ComponentType<{ embedded?: boolean }>;',
    '};',
    '',
    'export type RemoteLoader = () => Promise<RemoteModule>;',
    '',
    'export const remoteLoaders: Record<string, RemoteLoader> = {',
  ];
  for (const r of remotes) {
    const importPath = remoteImportPath(r.alias, r.expose);
    lines.push(`  ${JSON.stringify(r.alias)}: () =>`);
    lines.push(
      `    // @ts-expect-error Module Federation remote — resolved at runtime`,
    );
    lines.push(`    import(${JSON.stringify(importPath)}) as Promise<RemoteModule>,`);
  }
  lines.push('};');
  lines.push('');
  return `${lines.join('\n')}\n`;
}

module.exports = {
  DEMO_ALIAS,
  DEMO_URL_ENV,
  DEFAULT_EXPOSE,
  aliasToUrlEnv,
  defaultDemoRemote,
  normalizeRemoteEntry,
  remotesFromMeta,
  parseRemoteFlag,
  remoteImportPath,
  generateLoadersSource,
  isValidAlias,
  isValidExpose,
  isValidUrlEnv,
};
