import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

const SKIP = new Set([
  'node_modules',
  'dist',
  '.git',
  '.cursor',
  '.specify',
  '.tmp-tests',
  'playwright-report',
  'test-results',
  'starter.role.json',
  'coverage',
  '.vscode',
]);

function withTempCopy(fn) {
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'starter-add-remote-writes-'));
  fs.cpSync(ROOT, tmp, {
    recursive: true,
    filter: (src) => !SKIP.has(path.basename(src)),
  });
  try {
    return fn(tmp);
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true });
  }
}

function init(cwd, args) {
  return spawnSync('node', ['scripts/init.mjs', ...args], {
    cwd,
    encoding: 'utf8',
  });
}

function addRemote(cwd, args) {
  return spawnSync('node', ['scripts/add-remote.mjs', ...args], {
    cwd,
    encoding: 'utf8',
  });
}

function readMeta(cwd) {
  return JSON.parse(
    fs.readFileSync(path.join(cwd, 'starter.role.json'), 'utf8'),
  );
}

function envValue(cwd, key) {
  const text = fs.readFileSync(path.join(cwd, '.env'), 'utf8');
  const m = text.match(new RegExp(`^${key}=(.*)$`, 'm'));
  return m ? m[1].trim() : null;
}

test('success writes remotes[], .env urlEnv, and loaders.generated.ts', () => {
  withTempCopy((tmp) => {
    assert.equal(init(tmp, ['--role=shell', '--port=3001']).status, 0);
    const r = addRemote(tmp, [
      '--alias=demoRemote',
      '--name=demoRemote',
      '--port=3002',
    ]);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /Restart the shell/i);

    const meta = readMeta(tmp);
    assert.equal(meta.role, 'shell');
    assert.equal(meta.remotes.length, 1);
    assert.equal(meta.remotes[0].alias, 'demoRemote');
    assert.equal(meta.remotes[0].federationName, 'demoRemote');
    assert.equal(meta.remotes[0].expose, './DemoRemote');
    assert.equal(meta.remotes[0].urlEnv, 'DEMO_REMOTE_URL');

    assert.equal(
      envValue(tmp, 'DEMO_REMOTE_URL'),
      'http://127.0.0.1:3002/remoteEntry.js',
    );

    const loaders = fs.readFileSync(
      path.join(tmp, 'src/app/remotes/loaders.generated.ts'),
      'utf8',
    );
    assert.match(loaders, /Generated by init \/ add-remote/);
    assert.match(loaders, /demoRemote/);
    assert.match(loaders, /demoRemote\/DemoRemote/);
  });
});

test('two sequential adds leave both aliases in meta and loaders', () => {
  withTempCopy((tmp) => {
    assert.equal(init(tmp, ['--role=shell', '--port=3001']).status, 0);
    const first = addRemote(tmp, [
      '--alias=demoRemote',
      '--name=demoRemote',
      '--port=3002',
    ]);
    assert.equal(first.status, 0, first.stderr);

    const second = addRemote(tmp, [
      '--alias=billingRemote',
      '--name=demoRemote',
      '--federation-name=demoRemote',
      '--expose=./DemoRemote',
      '--port=3003',
    ]);
    assert.equal(second.status, 0, second.stderr);

    const meta = readMeta(tmp);
    assert.equal(meta.remotes.length, 2);
    assert.deepEqual(
      meta.remotes.map((r) => r.alias),
      ['demoRemote', 'billingRemote'],
    );

    assert.equal(
      envValue(tmp, 'DEMO_REMOTE_URL'),
      'http://127.0.0.1:3002/remoteEntry.js',
    );
    assert.equal(
      envValue(tmp, 'BILLING_REMOTE_URL'),
      'http://127.0.0.1:3003/remoteEntry.js',
    );

    const loaders = fs.readFileSync(
      path.join(tmp, 'src/app/remotes/loaders.generated.ts'),
      'utf8',
    );
    assert.match(loaders, /"demoRemote"/);
    assert.match(loaders, /"billingRemote"/);
  });
});

test('--url writes absolute URL to env', () => {
  withTempCopy((tmp) => {
    assert.equal(init(tmp, ['--role=shell', '--port=3001']).status, 0);
    const url = 'http://127.0.0.1:4000/remoteEntry.js';
    const r = addRemote(tmp, ['--alias=demoRemote', `--url=${url}`]);
    assert.equal(r.status, 0, r.stderr);
    assert.equal(envValue(tmp, 'DEMO_REMOTE_URL'), url);
  });
});
